import {
  Department,
  Doctor,
  MedicalService,
  CheckupPackage,
  MedicalEquipment,
  HealthArticle,
  AppointmentRecord,
  LabResult,
  AuditLogItem,
  CommercialTier,
} from './types';

export const HOSPITAL_INFO = {
  name: {
    fa: 'بیمارستان بین‌المللی ابن‌سینا',
    en: 'Avicenna International Hospital',
  },
  accreditation: {
    fa: 'دارنده نشان طلایی JCI و استاندارد بین‌المللی ISO 15189',
    en: 'Holder of JCI Gold Seal & ISO 15189 International Accreditation',
  },
  emergencyHotline: '1590',
  internationalCall: '+98 21 8899 7700',
  bedCount: 450,
  icuBeds: 64,
  activeSurgeons: 120,
  dailyTriageCapacity: 850,
  address: {
    fa: 'تهران، بزرگراه شهید همت، تقاطع بلوار سلامت، پردیس پزشکی ابن‌سینا',
    en: 'Avicenna Medical Campus, Salamat Blvd Intersection, Hemmat Expwy, Tehran',
  },
  workingHours: {
    fa: 'اورژانس، زایمان و ICU به‌صورت ۲۴ ساعته / کلینیک‌های تخصصی: ۸:۰۰ الی ۲۰:۰۰',
    en: 'Emergency & ICU 24/7 / Specialty Clinics: 08:00 to 20:00',
  },
};

export const DEPARTMENTS: Department[] = [
  {
    id: 'cardiology',
    name: { fa: 'مرکز جامع قلب و عروق', en: 'Comprehensive Heart & Vascular Center' },
    tagline: { fa: 'پیشرفته‌ترین مرکز آنژیوپلاستی و جراحی‌های کم‌تهاجمی دریچه', en: 'Advanced Angioplasty & Minimally Invasive Valve Surgeries' },
    description: {
      fa: 'مجهز به ۳ اتاق کاتتریسم بای‌پلین، بخش مراقبت‌های ویژه کرونری (CCU) و ریکاوری پیشرفته جراحی قلب باز با استانداردهای انجمن قلب آمریکا (AHA).',
      en: 'Equipped with 3 biplane catheterization labs, CCU, and advanced open-heart recovery conforming to AHA guidelines.',
    },
    icon: 'HeartPulse',
    headOfDepartment: { fa: 'پروفسور مسعود کیهانی', en: 'Prof. Masoud Keyhani' },
    bedCapacity: 75,
    floor: { fa: 'طبقه سوم، بال شرقی', en: '3rd Floor, East Wing' },
    features: {
      fa: ['آنژیوگرافی عروق کرونر و پریفرال ۲۴ ساعته', 'جراحی ترمیمی دریچه میترال بدون شکافتن جناغ', 'بخش الکتروفیزیولوژی و پیس‌میکر (EPS)'],
      en: ['24/7 Coronary & Peripheral Angiography', 'Minimally Invasive Mitral Valve Repair', 'Electrophysiology & Pacemaker Lab (EPS)'],
    },
    stats: [
      { label: { fa: 'نرخ موفقیت جراحی', en: 'Surgical Success' }, value: '99.4%' },
      { label: { fa: 'آنژیوگرافی سالانه', en: 'Annual Angioplasties' }, value: '+4,200' },
    ],
  },
  {
    id: 'oncology',
    name: { fa: 'انستیتو کانسر و ژن‌درمانی', en: 'Cancer Institute & Gene Therapy' },
    tagline: { fa: 'درمان‌های نوین هدفمند، پرتودرمانی تطبیقی و پاتولوژی مولکولی', en: 'Targeted Therapies, Adaptive Radiotherapy & Molecular Pathology' },
    description: {
      fa: 'ارائه مراقبت‌های جامع سرطان در قالب توموربوردهای هفتگی با مشارکت آنکولوژیست‌ها، جراحان، پاتولوژیست‌ها و متخصصین ژنتیک پزشکی.',
      en: 'Comprehensive oncology care featuring weekly multidisciplinary tumor boards uniting oncologists, surgeons, and geneticists.',
    },
    icon: 'ShieldPlus',
    headOfDepartment: { fa: 'دکتر پروانه علیزاده', en: 'Dr. Parvaneh Alizadeh' },
    bedCapacity: 60,
    floor: { fa: 'طبقه همکف و منفی یک، پردیس فارابی', en: 'Ground & B1 Floor, Farabi Pavilion' },
    features: {
      fa: ['سیستم شتاب‌دهنده خطی TrueBeam و رادیوتراپی دقیق IMRT', 'شیمی‌درمانی سرپایی در اتاق‌های VIP ایزوله', 'آزمایشگاه توالی‌یابی ژنومی فردمحور (NGS)'],
      en: ['Varian TrueBeam Linear Accelerator & IMRT', 'Outpatient Chemotherapy in Isolated VIP Suites', 'Next-Gen Genomic Sequencing Lab (NGS)'],
    },
    stats: [
      { label: { fa: 'کمیته‌های مشترک توموربورد', en: 'Multidisciplinary Boards' }, value: 'هفتگی / Weekly' },
      { label: { fa: 'نرخ بقای ۵ ساله در گرید ۱ و ۲', en: '5-Yr Survival (Stage I-II)' }, value: '94.8%' },
    ],
  },
  {
    id: 'robotic-surgery',
    name: { fa: 'مرکز جراحی‌های روباتیک و لاپاراسکوپی', en: 'Robotic & Laparoscopic Surgery Center' },
    tagline: { fa: 'دقت میلی‌متری با سامانه جراحی هوشمند Da Vinci Xi', en: 'Sub-millimeter Precision with Da Vinci Xi Surgical Suite' },
    description: {
      fa: 'انجام جراحی‌های اورولوژی، توراکس و گوارش با حداقل آسیب بافتی، کاهش چشمگیر درد پس از عمل و ترخیص زودهنگام بیماران.',
      en: 'Pioneering robotic-assisted urology, thoracic, and GI procedures with minimal incision, reduced postoperative pain, and rapid recovery.',
    },
    icon: 'Cpu',
    headOfDepartment: { fa: 'دکتر آرش پارسانیا', en: 'Dr. Arash Parsania' },
    bedCapacity: 45,
    floor: { fa: 'طبقه چهارم، مجموعه اتاق‌های عمل ماژولار', en: '4th Floor, Modular OR Complex' },
    features: {
      fa: ['جراحی روباتیک پروستاتکتومی رادیکال با حفظ عصب', 'لاپاراسکوپی پیشرفته دستگاه گوارش و باریاتریک', 'دوربین‌های سه‌بعدی اولترا اچ‌دی با دید ۱۰ برابری'],
      en: ['Nerve-sparing Robotic Radical Prostatectomy', 'Advanced Laparoscopic Bariatric & GI Procedures', '10x Magnified 3D Ultra-HD Surgical Visualization'],
    },
    stats: [
      { label: { fa: 'کاهش زمان بستری', en: 'Length of Stay Reduction' }, value: '62%' },
      { label: { fa: 'جراحی بدون نیاز به تزریق خون', en: 'Bloodless Surgeries' }, value: '98.1%' },
    ],
  },
  {
    id: 'neurosciences',
    name: { fa: 'انستیتو علوم اعصاب و جراحی مغز', en: 'Neuroscience & Neurosurgery Institute' },
    tagline: { fa: 'جراحی قاعده جمجمه با نویگیشن تصویربرداری حین عمل (Intra-op MRI)', en: 'Skull Base Surgery with Intraoperative MRI Guidance' },
    description: {
      fa: 'تجهیز اتاق عمل هیبرید به سامانه تصویربرداری مغزی آنلاین، میکروسکوپ‌های جراحی KINEVO 900 و پایش مداوم الکتروفیزیولوژی سیستم عصبی.',
      en: 'Hybrid neuro-suite integrated with intra-op imaging, Zeiss KINEVO 900 surgical microscopes, and real-time intraoperative neuromonitoring.',
    },
    icon: 'Activity',
    headOfDepartment: { fa: 'پروفسور بیژن جهانگیرپور', en: 'Prof. Bijan Jahangirpour' },
    bedCapacity: 50,
    floor: { fa: 'طبقه دوم، بال غربی', en: '2nd Floor, West Wing' },
    features: {
      fa: ['جراحی تومورهای مغزی در حالت هوشیاری بیمار (Awake Craniotomy)', 'درمان فوق‌تخصصی سکته مغزی حاد در کمتر از ۶۰ دقیقه (Code Stroke)', 'کلینیک صرع مقاوم به درمان و کاشت تراشه‌های عصبی VNS'],
      en: ['Awake Craniotomy for Eloquent Cortex Tumors', 'Acute Stroke Golden-Hour Code Interventions (<60m)', 'Refractory Epilepsy & Vagus Nerve Stimulation (VNS)'],
    },
    stats: [
      { label: { fa: 'پاسخ طلایی درمان استروک', en: 'Stroke Door-to-Needle' }, value: '38 دقیقه' },
      { label: { fa: 'پایش نوروفیزیولوژی پیوسته', en: 'Neuro-Monitoring Rate' }, value: '100%' },
    ],
  },
  {
    id: 'transplant',
    name: { fa: 'مرکز پیوند اعضا و پزشکی بازساختی', en: 'Organ Transplant & Regenerative Medicine' },
    tagline: { fa: 'پیوند کبد، کلیه، قرنیه و سلول‌های بنیادی با بالاترین استانداردهای ایمنی', en: 'Liver, Kidney, Cornea & Stem Cell Transplantation' },
    description: {
      fa: 'واحد مراقبت‌های ویژه ایزوله پیوند مجهز به سیستم فیلتراسیون جریان لامینار HEPA و بانک جامع سلول‌های بنیادی بند ناف.',
      en: 'HEPA-filtered positive pressure transplant ICU with on-site histocompatibility (HLA) testing and cell therapy laboratories.',
    },
    icon: 'Dna',
    headOfDepartment: { fa: 'دکتر فرشاد افشارمنش', en: 'Dr. Farshad Afsharmanesh' },
    bedCapacity: 35,
    floor: { fa: 'طبقه پنجم، سوئیت‌های ایزوله استریل', en: '5th Floor, Sterile Isolated Wing' },
    features: {
      fa: ['پیوند کبد از دهنده زنده و متوفی با متد اسپیلیت', 'آزمایشگاه سازگاری نسجی (HLA) بلادرنگ', 'سلول‌درمانی غضروف مفاصل و ترمیم بافت قلبی'],
      en: ['Living Donor & Split Deceased Liver Transplants', 'Real-time High-Resolution HLA Typing Lab', 'Mesenchymal Stem Cell Cartilage & Cardiac Repair'],
    },
    stats: [
      { label: { fa: 'بقای ۱ ساله پیوند کلیه و کبد', en: '1-Year Graft Survival' }, value: '97.2%' },
      { label: { fa: 'پیوند انجام شده در ۳ سال گذشته', en: 'Transplants in 3 Yrs' }, value: '+680' },
    ],
  },
  {
    id: 'women-children',
    name: { fa: 'مرکز مادر، جنین و نوزادان نارس', en: 'Maternal, Fetal & Neonatal Institute' },
    tagline: { fa: 'واحدهای LDR تک‌نفره زایمان فیزیولوژیک و NICU سطح ۳ پیشرفته', en: 'Private LDR Suites for Natural Birth & Level III Neonatal ICU' },
    description: {
      fa: 'ارائه بسته‌های زایمان ایمن بدون درد، جراحی‌های جنینی داخل رحمی و مراقبت فوق‌تخصصی از نوزادان بسیار کم‌وزن (ELBW) از هفته ۲۴ بارداری.',
      en: 'Painless delivery suites, advanced intrauterine fetal surgery, and Level III NICU specialized in caring for micro-preemies from 24 weeks.',
    },
    icon: 'Baby',
    headOfDepartment: { fa: 'دکتر مریم سادات میرمحمدی', en: 'Dr. Maryam Sadat Mirmohammadi' },
    bedCapacity: 65,
    floor: { fa: 'طبقه اول، بلوک B مادر و کودک', en: '1st Floor, Block B Mother & Child' },
    features: {
      fa: ['سوئیت‌های لوکس اقامت اختصاصی خانواده (LDR)', 'غربالگری سلامت ژنتیکی جنین با فناوری NIPT و آمنیوسنتز', 'بخش NICU مجهز به تهویه مکانیکی نوسانی فرکانس‌بالا (HFOV)'],
      en: ['Private Family-Centered LDR Delivery Rooms', 'Non-Invasive Prenatal Genetic Testing (NIPT)', 'HFOV High-Frequency Oscillatory Ventilators in NICU'],
    },
    stats: [
      { label: { fa: 'نجات نوزادان نارس <1000g', en: 'Survival for <1000g Preemies' }, value: '91.8%' },
      { label: { fa: 'زایمان‌های فیزیولوژیک طبیعی', en: 'Natural Delivery Rate' }, value: '74%' },
    ],
  },
];

export const DOCTORS: Doctor[] = [
  {
    id: 'doc-keyhani',
    name: { fa: 'پروفسور مسعود کیهانی', en: 'Prof. Masoud Keyhani' },
    title: { fa: 'فوق‌تخصص جراحی قلب و عروق و پیوند قلب', en: 'Cardiothoracic & Heart Transplant Surgeon' },
    medicalCouncilCode: 'IR-MC-34291',
    departmentId: 'cardiology',
    specialty: { fa: 'جراحی قلب و عروق', en: 'Cardiovascular Surgery' },
    subSpecialty: { fa: 'جراحی‌های کم‌تهاجمی و تعویض ترانس‌کاتتر دریچه (TAVI)', en: 'Minimally Invasive & TAVI Procedures' },
    experienceYears: 26,
    academicRank: { fa: 'استاد تمام و عضو هیئت‌مدیره انجمن جراحان قلب', en: 'Full Professor & Board Member of CTS' },
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    bio: {
      fa: 'بیش از ۶۰۰۰ عمل جراحی قلب باز موفق، فلوشیپ تخصصی جراحی آئورت از دانشگاه هانوفر آلمان و پیشگام روش‌های نوین جراحی بدون پمپ در خاورمیانه.',
      en: 'Over 6,000 successful open-heart procedures, aortic fellowship from Hannover Medical School, and pioneer of off-pump CABG in the region.',
    },
    languages: ['فارسی', 'English', 'Deutsch'],
    consultationTypes: ['in-person', 'telemedicine'],
    rating: 4.96,
    satisfactionRate: 99.1,
    availableDays: { fa: 'شنبه، دوشنبه، چهارشنبه (صبح)', en: 'Sat, Mon, Wed (Morning)' },
    workingSlots: ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30'],
    roomNumber: 'کلینیک قلب - اتاق ۳۰۴',
  },
  {
    id: 'doc-alizadeh',
    name: { fa: 'دکتر پروانه علیزاده', en: 'Dr. Parvaneh Alizadeh' },
    title: { fa: 'فوق‌تخصص انکولوژی و هماتولوژی بالینی', en: 'Clinical Hematologist & Medical Oncologist' },
    medicalCouncilCode: 'IR-MC-49120',
    departmentId: 'oncology',
    specialty: { fa: 'انکولوژی و سرطان‌شناسی', en: 'Medical Oncology' },
    subSpecialty: { fa: 'ایمونوتراپی و درمان‌های بیولوژیک هدفمند', en: 'Immunotherapy & Targeted Biologics' },
    experienceYears: 19,
    academicRank: { fa: 'دانشیار دانشگاه علوم پزشکی و پژوهشگر مرکز ژنومیک', en: 'Associate Professor & Genomic Researcher' },
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400',
    bio: {
      fa: 'دارنده بورد تخصصی انکولوژی، رئیس کمیته بین‌المللی توموربورد سرطان پستان و نویسنده بیش از ۳۵ مقاله در ژورنال‌های معتبر لَنست و نیچر مدیسین.',
      en: 'Certified in Clinical Oncology, Chair of the Breast Tumor Board, author of 35+ publications in The Lancet and Nature Medicine.',
    },
    languages: ['فارسی', 'English', 'Français'],
    consultationTypes: ['in-person', 'telemedicine'],
    rating: 4.93,
    satisfactionRate: 98.6,
    availableDays: { fa: 'یک‌شنبه، سه‌شنبه، پنج‌شنبه (عصر)', en: 'Sun, Tue, Thu (Afternoon)' },
    workingSlots: ['15:00', '15:30', '16:00', '16:30', '17:00', '17:30'],
    roomNumber: 'کلینیک انکولوژی - اتاق ۱۱۲',
  },
  {
    id: 'doc-parsania',
    name: { fa: 'دکتر آرش پارسانیا', en: 'Dr. Arash Parsania' },
    title: { fa: 'فوق‌تخصص جراحی روباتیک اورولوژی و پیوند کلیه', en: 'Robotic Urologic Surgeon & Kidney Transplant' },
    medicalCouncilCode: 'IR-MC-58721',
    departmentId: 'robotic-surgery',
    specialty: { fa: 'اورولوژی و جراحی روباتیک', en: 'Urology & Robotic Surgery' },
    subSpecialty: { fa: 'پروستاتکتومی روباتیک و انکولوژی کلیه', en: 'Robotic Prostatectomy & Renal Oncology' },
    experienceYears: 17,
    academicRank: { fa: 'استاد وابسته جراحی و مربی بین‌المللی جراحی روباتیک داوینچی', en: 'Adjunct Professor & Certified Da Vinci Proctor' },
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=400',
    bio: {
      fa: 'انجام بیش از ۱۲۰۰ عمل موفقیت‌آمیز با روبات جراحی داوینچی، فارغ‌التحصیل دانشگاه جانز هاپکینز و عضو فعال انجمن اورولوژی اروپا (EAU).',
      en: 'Over 1,200 robotic procedures executed, Johns Hopkins fellow and European Association of Urology (EAU) active committee member.',
    },
    languages: ['فارسی', 'English'],
    consultationTypes: ['in-person'],
    rating: 4.98,
    satisfactionRate: 99.4,
    availableDays: { fa: 'شنبه و سه‌شنبه (صبح و عصر)', en: 'Sat & Tue (Full Day)' },
    workingSlots: ['10:00', '10:30', '11:00', '14:00', '14:30', '15:00'],
    roomNumber: 'کلینیک جراحی - اتاق ۴۱۵',
  },
  {
    id: 'doc-jahangir',
    name: { fa: 'پروفسور بیژن جهانگیرپور', en: 'Prof. Bijan Jahangirpour' },
    title: { fa: 'فوق‌تخصص جراحی میکروسکوپی مغز و قاعده جمجمه', en: 'Microsurgical Neurosurgeon & Skull Base Specialist' },
    medicalCouncilCode: 'IR-MC-21804',
    departmentId: 'neurosciences',
    specialty: { fa: 'جراحی مغز و اعصاب', en: 'Neurosurgery' },
    subSpecialty: { fa: 'جراحی تومورهای هیپوفیز، عصب شنوایی و عروق مغزی', en: 'Pituitary, Acoustic Neuroma & Cerebrovascular' },
    experienceYears: 31,
    academicRank: { fa: 'استاد برجسته و رئیس سابق دپارتمان جراحی اعصاب', en: 'Distinguished Professor & Former Chair of Neurosurgery' },
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400',
    bio: {
      fa: 'پیشگام ملی روش‌های جراحی آندوسکوپیک مغز، بیش از ۸۵۰۰ عمل حساس مغز و نخاع و عضو افتخاری فدراسیون جهانی انجمن‌های جراحی اعصاب (WFNS).',
      en: 'Pioneer of endoscopic cranial surgery, 8,500+ complex neurosurgical cases, Honorary Fellow of World Federation of Neurosurgical Societies.',
    },
    languages: ['فارسی', 'English', 'العربية'],
    consultationTypes: ['in-person', 'telemedicine'],
    rating: 4.99,
    satisfactionRate: 99.7,
    availableDays: { fa: 'دوشنبه و چهارشنبه (صبح)', en: 'Mon & Wed (Morning)' },
    workingSlots: ['08:30', '09:00', '09:30', '10:00', '10:30'],
    roomNumber: 'کلینیک مغز و اعصاب - اتاق ۲۰۲',
  },
  {
    id: 'doc-mirmohammadi',
    name: { fa: 'دکتر مریم سادات میرمحمدی', en: 'Dr. Maryam Sadat Mirmohammadi' },
    title: { fa: 'فوق‌تخصص طب مادر و جنین (پریناتولوژی)', en: 'Maternal-Fetal Medicine (Perinatology)' },
    medicalCouncilCode: 'IR-MC-62409',
    departmentId: 'women-children',
    specialty: { fa: 'زنان، زایمان و پریناتولوژی', en: 'Obstetrics & Gynecology' },
    subSpecialty: { fa: 'بارداری‌های پرخطر، سونوگرافی کالرداپلر جنین و اکوکاردیوگرافی قلب جنین', en: 'High-Risk Pregnancy, Fetal Doppler & Echo' },
    experienceYears: 16,
    academicRank: { fa: 'دانشیار دانشگاه و مسئول برنامه زایمان ایمن ابن‌سینا', en: 'Associate Professor & Director of Safe Birth Program' },
    avatar: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&q=80&w=400',
    bio: {
      fa: 'متخصص مدیریت زایمان‌های پرخطر مادران با بیماری‌های زمینه‌ای، فلوشیپ پریناتولوژی از بیمارستان سلطنتی لندن و حامی زایمان فیزیولوژیک طبیعی.',
      en: 'Specialized in high-risk maternal comorbidities, perinatology fellowship from Royal London Hospital, advocate of gentle natural birth.',
    },
    languages: ['فارسی', 'English'],
    consultationTypes: ['in-person', 'telemedicine'],
    rating: 4.95,
    satisfactionRate: 99.0,
    availableDays: { fa: 'شنبه تا چهارشنبه (صبح و عصر)', en: 'Sat to Wed (Morning & Afternoon)' },
    workingSlots: ['10:00', '10:30', '11:00', '11:30', '16:00', '16:30', '17:00'],
    roomNumber: 'کلینیک مادر و جنین - اتاق ۱۰۵',
  },
  {
    id: 'doc-afsharmanesh',
    name: { fa: 'دکتر فرشاد افشارمنش', en: 'Dr. Farshad Afsharmanesh' },
    title: { fa: 'فوق‌تخصص جراحی هپاتوبانکراتوبیلیاری (HPB) و پیوند کبد', en: 'Hepato-Pancreato-Biliary & Liver Transplant Surgeon' },
    medicalCouncilCode: 'IR-MC-41556',
    departmentId: 'transplant',
    specialty: { fa: 'جراحی عمومی و پیوند اعضا', en: 'Transplant Surgery' },
    subSpecialty: { fa: 'پیوند کبد اطفال و بزرگسالان، جراحی‌های پیچیده پانکراس', en: 'Pediatric & Adult Liver Transplant, Pancreatic Surgery' },
    experienceYears: 22,
    academicRank: { fa: 'استاد تمام جراحی و سرپرست تیم پیوند بیمارستان', en: 'Professor of Surgery & Head of Transplant Team' },
    avatar: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&q=80&w=400',
    bio: {
      fa: 'بیش از ۷۰۰ پیوند کبد موفق با میزان بقای بیش از ۹۶٪ در سال نخست، دوره پیشرفته پیوند کبد از دانشگاه کیوتو ژاپن و پژوهشگر ارشد در سلول‌های بنیادی کبد.',
      en: '700+ successful liver transplants with 96%+ 1-year graft survival, advanced living-donor fellowship from Kyoto University.',
    },
    languages: ['فارسی', 'English', 'Japanese'],
    consultationTypes: ['in-person'],
    rating: 4.97,
    satisfactionRate: 99.3,
    availableDays: { fa: 'یک‌شنبه و چهارشنبه (صبح)', en: 'Sun & Wed (Morning)' },
    workingSlots: ['09:00', '09:30', '10:00', '10:30', '11:00'],
    roomNumber: 'کلینیک پیوند - اتاق ۵۰۸',
  },
];

export const MEDICAL_SERVICES: MedicalService[] = [
  {
    id: 'srv-angio',
    departmentId: 'cardiology',
    name: { fa: 'آنژیوگرافی و آنژیوپلاستی عروق کرونر (Stent)', en: 'Coronary Angiography & Drug-Eluting Stenting' },
    description: {
      fa: 'تصویربرداری فوق‌سریع دیجیتال از عروق تغذیه‌کننده قلب با امکان بالون‌زدن و کارگذاری استنت دارویی جذبی در همان جلسه.',
      en: 'Rapid high-definition fluoroscopic imaging with immediate bio-absorbable drug-eluting stent implantation capability.',
    },
    durationMin: 45,
    preparationNotes: { fa: '۶ ساعت ناشتایی کامل، همراه داشتن آخرین آزمایش‌های کلیوی و نوار قلب', en: '6 hours fasting, bring recent renal panel and ECG' },
    category: 'therapeutic',
    accreditedLab: true,
  },
  {
    id: 'srv-petct',
    departmentId: 'oncology',
    name: { fa: 'تصویربرداری توموگرافی انتشار پوزیترون (PET-CT)', en: 'Whole-Body PET-CT Molecular Imaging' },
    description: {
      fa: 'بررسی متابولیسم گلوکز در سلول‌ها با رادیوداروی 18F-FDG برای تشخیص مرحله سرطان و پاسخ به درمان با حساسیت بیش از ۹۸٪.',
      en: 'Metabolic staging of malignancy with 18F-FDG radio-tracer to assess tumor response and recurrence at sub-cellular level.',
    },
    durationMin: 90,
    preparationNotes: { fa: 'رعایت رژیم کم‌کربوهیدرات از ۲۴ ساعت قبل و کنترل قند خون زیر ۱۸۰', en: 'Low-carb diet 24h prior, blood glucose must be <180 mg/dL' },
    category: 'diagnostic',
    accreditedLab: true,
  },
  {
    id: 'srv-robotic-prostate',
    departmentId: 'robotic-surgery',
    name: { fa: 'پروستاتکتومی رادیکال با روبات جراحی داوینچی', en: 'Da Vinci Robotic Nerve-Sparing Radical Prostatectomy' },
    description: {
      fa: 'برداشتن کامل تومور پروستات با حفظ کامل اعصاب ارکشن و اسفنکتر ادراری با دید سه‌بعدی میکروسکوپی و حرکات ۷ درجه آزادی.',
      en: 'Complete tumor excision with preservation of neurovascular bundles for urinary continence and sexual function recovery.',
    },
    durationMin: 180,
    category: 'surgical',
  },
  {
    id: 'srv-awake-craniotomy',
    departmentId: 'neurosciences',
    name: { fa: 'کرانیوتومی در حالت بیداری با نقشه‌برداری کورتکس مغز', en: 'Awake Craniotomy with Direct Cortical Speech Mapping' },
    description: {
      fa: 'جراحی تومورهای مجاور مراکز تکلم و حرکت مغز در حالی که بیمار با نوروسایکولوژیست گفتگو می‌کند تا هیچ آسیبی به عملکردهای حیاتی نرسد.',
      en: 'Neurosurgical tumor resection adjacent to critical language and motor areas with continuous awake verbal engagement.',
    },
    durationMin: 240,
    category: 'surgical',
  },
  {
    id: 'srv-liver-tx',
    departmentId: 'transplant',
    name: { fa: 'پیوند کبد اورژانس و الکتیو', en: 'Living Donor & Cadaveric Liver Transplantation' },
    description: {
      fa: 'جراحی جایگزینی کبد نارس با کبد سالم توسط تیم جراحی، بیهوشی پیوند و پرفیوژنیست در اتاق عمل اختصاصی پیوند اعضا.',
      en: 'Full-spectrum end-stage liver disease surgical intervention backed by specialized transplant intensive care.',
    },
    durationMin: 360,
    category: 'surgical',
  },
  {
    id: 'srv-water-birth',
    departmentId: 'women-children',
    name: { fa: 'زایمان فیزیولوژیک در آب و زایمان بدون درد با اسپاینال', en: 'Gentle Water Birth & Walking Epidural Suites' },
    description: {
      fa: 'زایمان در وان‌های استاندارد هیدروتراپی با حضور مامای همراه، رایحه‌درمانی، ورزش‌های تخصصی لگن و امکان بی‌حسی کنترل‌شده توسط مادر.',
      en: 'Hydrotherapy delivery suites with one-on-one midwife presence, active pelvic mechanics, and patient-controlled epidural analgesia.',
    },
    durationMin: 120,
    category: 'therapeutic',
  },
];

export const CHECKUP_PACKAGES: CheckupPackage[] = [
  {
    id: 'pkg-cardio-gold',
    name: { fa: 'پکیج سلامت طلایی قلب و عروق ابن‌سینا', en: 'Avicenna Gold Cardiovascular Check-up' },
    targetAudience: { fa: 'افراد بالای ۳۵ سال، مبتلایان به فشار خون، قند خون یا سابقه خانوادگی سکته', en: 'Ages 35+, individuals with hypertension, dyslipidemia or family history' },
    description: {
      fa: 'بررسی جامع عروق کرونر، سلامت ساختاری دریچه‌ها، تست ورزش دینامیک و آزمایش‌های بیوشیمیایی مارکرهای ترومبوز و التهاب عروق.',
      en: 'Complete coronary risk stratification, 4D echocardiography, treadmill stress test, and high-sensitivity inflammation biomarkers.',
    },
    testsCount: 22,
    features: {
      fa: [
        'اکوکاردیوگرافی ۴ بعدی داپلر بافت',
        'تست ورزش استاندارد قلبی (Treadmill Test)',
        'آنالیز ترکیب چربی‌ها (Lipid Profile Extended) و Apo-B',
        'سنجش پروتئین فاز حاد hs-CRP و هموسیستئین',
        'مشاوره جامع تغذیه بالینی و سبک زندگی قلب',
      ],
      en: [
        '4D Tissue Doppler Echocardiography',
        'Treadmill Cardiac Stress Testing',
        'Extended Lipid Subfractions & Apolipoprotein B',
        'High-Sensitivity hs-CRP & Homocysteine Markers',
        'Personalized Clinical Cardiology & Nutrition Consult',
      ],
    },
    durationHours: 4,
    badge: { fa: 'پرفروش‌ترین / Most Requested', en: 'Top Tier Screening' },
    price: { fa: '۴,۸۵۰,۰۰۰ تومان', en: '$120 USD' },
  },
  {
    id: 'pkg-executive-vip',
    name: { fa: 'پکیج جامع اکزکیوتیو پریمیوم (Executive VIP)', en: 'Executive Comprehensive VIP Wellness' },
    targetAudience: { fa: 'مدیران ارشد، کارآفرینان و افرادی که به پایش همه‌جانبه سیستم‌های زیستی اهمیت می‌دهند', en: 'Executives, entrepreneurs and individuals seeking 360-degree biological profiling' },
    description: {
      fa: 'غربالگری فراگیر شامل اسکن‌های کم‌پرتو قفسه سینه، کولونوسکوپی در بیهوشی، پانل ژنومیک پیشگیری و ویزیت توسط ۵ استاد هیئت علمی در سوئیت اختصاصی.',
      en: 'Whole-body low-dose CT chest, painless sedated endoscopy/colonoscopy, cancer tumor markers, and VIP lounge hospitality.',
    },
    testsCount: 48,
    features: {
      fa: [
        'سی‌تی‌اسکن ریه کم‌پرتو (Low-Dose CT) و سونوگرافی کامل شکم و لگن',
        'کولونوسکوپی و آندوسکوپی فوقانی با بیهوشی ملایم',
        'پانل جامع مارکرهای تومور (PSA, CEA, CA 19-9, CA 125, AFP)',
        'بررسی تراکم مواد معدنی استخوان (DEXA Scan)',
        'اقامت در سوئیت اختصاصی VIP با صبحانه و پذیرایی سالم',
      ],
      en: [
        'Low-Dose Chest CT & Abdominopelvic High-Res Ultrasound',
        'Painless Propofol-Sedated Video Endoscopy & Colonoscopy',
        'Multi-organ Tumor Marker Screening Suite (PSA, CEA, CA19-9)',
        'Dual-energy X-ray Absorptiometry (DEXA) Bone Density',
        'Dedicated Private Executive Suite with Healthy Gourmet Catering',
      ],
    },
    durationHours: 6,
    badge: { fa: 'جامع‌ترین غربالگری / 360 Screening', en: 'Flagship Check-up' },
    price: { fa: '۱۱,۹۰۰,۰۰۰ تومان', en: '$290 USD' },
  },
  {
    id: 'pkg-women-wellness',
    name: { fa: 'پکیج تخصصی سلامت و نشاط بانوان', en: 'Women Specialized Wellness & Prevention' },
    targetAudience: { fa: 'بانوان در سنین باروری و پس از یائسگی جهت ارزیابی سرطان‌های شایع و هورمون‌ها', en: 'Women at all life stages for early gynecologic, breast, and hormonal screening' },
    description: {
      fa: 'ماموگرافی سه‌بعدی توموسنتزیس دیجیتال با کمترین فشار بافت، پاپ اسمیر مبتنی بر مایع همراه با تعیین تیپ HPV و ارزیابی هورمونی تخمدان.',
      en: 'Low-dose 3D breast tomosynthesis, liquid-based cytology with high-risk HPV genotyping, and complete reproductive hormone profile.',
    },
    testsCount: 26,
    features: {
      fa: [
        'ماموگرافی دیجیتال توموسنتزیس ۳ بعدی (Hologic)',
        'سونوگرافی اختصاصی پستان و اندام‌های لگنی',
        'تست پاپ‌اسمیر ThinPrep به همراه ژنوتایپینگ ویروس HPV',
        'پانل هورمون‌های تیروئید و تخمدان (FSH, LH, AMH, TSH)',
        'مشاوره فوق‌تخصص انکولوژی زنان و مامایی',
      ],
      en: [
        '3D Digital Breast Tomosynthesis (Hologic)',
        'Pelvic & Transvaginal Ultrasound by Female Sonologist',
        'ThinPrep Pap Test with High-Risk HPV DNA Genotyping',
        'Complete Ovarian Reserve & Thyroid Hormone Panel (AMH, FSH)',
        'Private Consultation with Female Gynecologic Specialist',
      ],
    },
    durationHours: 3,
    badge: { fa: 'پیشنهاد ویژه بانوان', en: 'Dedicated to Women' },
    price: { fa: '۵,۴۰۰,۰۰۰ تومان', en: '$135 USD' },
  },
];

export const MEDICAL_EQUIPMENT: MedicalEquipment[] = [
  {
    id: 'eq-mri',
    name: { fa: 'ام‌آرآی ۳ تسلا مگنتوم ویدا (Siemens Magnetom Vida 3T)', en: 'Siemens Magnetom Vida 3-Tesla MRI' },
    model: 'Magnetom Vida 3T with BioMatrix Technology',
    manufacturer: 'Siemens Healthineers - Germany',
    description: {
      fa: 'اولین ام‌آرآی مجهز به هوش مصنوعی BioMatrix در کشور که به‌طور خودکار الگوهای تنفسی بیمار را ردیابی کرده و تصویربرداری با وضوح فوق‌العاده بالا را بدون نیاز به حبس نفس انجام می‌دهد.',
      en: 'BioMatrix technology that automatically adapts to patient respiratory patterns, delivering sub-millimeter neuro, cardiac, and musculoskeletal scans without breath-holding stress.',
    },
    capabilities: {
      fa: ['ام‌آرآی فانکشنال مغز (fMRI) جهت نقشه‌برداری حین جراحی', 'ام‌آر اسپکتروسکوپی برای تشخیص نوع بافت تومورها', 'ام‌آرآی قلب با ارزیابی دقیق فیبروز میوکارد'],
      en: ['Functional Brain fMRI for Pre-surgical Mapping', 'In-vivo MR Spectroscopy for Tumor Biochemical Profiling', 'Cardiac MRI with Quantitative Late Gadolinium Enhancement'],
    },
    departmentId: 'neurosciences',
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'eq-davinci',
    name: { fa: 'روبات جراحی پیشرفته داوینچی Xi (Intuitive Da Vinci Xi)', en: 'Intuitive Da Vinci Xi Robotic Surgical System' },
    model: 'Da Vinci Xi Multi-Quadrant Surgical Platform',
    manufacturer: 'Intuitive Surgical - USA',
    description: {
      fa: 'کامل‌ترین ربات جراحی دنیا با بازوهای مفصلی EndoWrist که دامنه حرکتی فراتر از مچ دست انسان دارند و بدون کمترین لرزش دست، عمل‌های بسیار پیچیده را با برش‌های نیم‌سانتی‌متری ممکن می‌سازند.',
      en: 'EndoWrist instruments with 7 degrees of freedom, tremor filtration, and intuitive motion scaling that allow surgeons to operate with unprecedented precision inside tight cavities.',
    },
    capabilities: {
      fa: ['جراحی تومورهای عمقی لگن و قفسه سینه', 'دید استریوسکوپیک سه‌بعدی با وضوح 4K', 'کاهش درد و خطر عفونت بیمار تا ۸۰٪'],
      en: ['Deep Pelvic, Thoracic and Esophageal Oncology', 'Dual-Console Capability for Live Surgical Proctoring', '80% Reduction in Postoperative Surgical Complications'],
    },
    departmentId: 'robotic-surgery',
    image: 'https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'eq-truebeam',
    name: { fa: 'شتاب‌دهنده خطی واریان ترو بیم (Varian TrueBeam STx)', en: 'Varian TrueBeam STx Radiosurgery System' },
    model: 'TrueBeam STx with PerfectPitch 6-DoF Couch',
    manufacturer: 'Varian Medical Systems - USA',
    description: {
      fa: 'دستگاه شتاب‌دهنده پرتو با سیستم هدایت تصویر بلادرنگ که تومورهای متحرک ریه و کبد را با سرعت چرخش بالا و دقت میکرومتری هدف قرار داده و بافت سالم مجاور را کاملاً محافظت می‌کند.',
      en: 'Sub-millimeter targeting with real-time breathing gating for stereotactic body radiation therapy (SBRT), minimizing toxic dose to surrounding healthy critical structures.',
    },
    capabilities: {
      fa: ['رادیوجراحی استریوتاکتیک کل بدن (SBRT/SRS)', 'کوتاه شدن زمان هر جلسه رادیوتراپی به کمتر از ۵ دقیقه', 'کولیماتور چندبرگی High-Definition (HD120 MLC)'],
      en: ['High-dose Hypofractionated Stereotactic Radiosurgery', 'RapidArc Dynamic Arc Therapy in under 5 minutes', 'High-Definition HD120 Multi-Leaf Collimator Beam Shaping'],
    },
    departmentId: 'oncology',
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=600',
  },
];

export const HEALTH_ARTICLES: HealthArticle[] = [
  {
    id: 'art-heart-signs',
    title: {
      fa: 'علائم پنهان ایسکمی قلب در بانوان و جوانان: چرا نباید منتظر درد شدید قفسه سینه ماند؟',
      en: 'Atypical Symptoms of Coronary Ischemia: Why You Shouldn’t Wait for Crushing Chest Pain',
    },
    category: { fa: 'قلب و عروق', en: 'Cardiology' },
    excerpt: {
      fa: 'درد در فک تحتانی، خستگی مفرط غیرمنتظره و تنگی نفس حین فعالیت‌های معمول می‌توانند اولین زنگ خطرهای آنژین ناپایدار باشند.',
      en: 'Jaw discomfort, sudden unexplained fatigue, and shortness of breath during routine chores can be early warnings of unstable angina.',
    },
    author: { fa: 'دکتر شیوا رادمنش (متخصص قلب)', en: 'Dr. Shiva Radmanesh, Cardiologist' },
    reviewer: { fa: 'پروفسور مسعود کیهانی (رئیس مرکز قلب)', en: 'Reviewed by Prof. Masoud Keyhani' },
    readTimeMin: 6,
    publishDate: '۱۴۰۳/۰۶/۲۵',
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&q=80&w=600',
    status: 'PUBLISHED',
  },
  {
    id: 'art-immunotherapy',
    title: {
      fa: 'انقلاب ایمونوتراپی در مهار بدخیمی‌ها: چگونه سلول‌های دفاعی خود بیمار سرطان را ریشه‌کن می‌کنند؟',
      en: 'The Immunotherapy Revolution: Training Your Own Immune System to Eradicate Cancer Cells',
    },
    category: { fa: 'انکولوژی مولکولی', en: 'Oncology' },
    excerpt: {
      fa: 'داروهای مهارکننده چک‌پوینت ایمنی (Checkpoint Inhibitors) با خنثی کردن ترفندهای استتاری تومور، لنفوسیت‌های T را برای شکار سلول‌های بدخیم فعال می‌سازند.',
      en: 'Checkpoint inhibitors strip cancer cells of their cloaking shields, unleashing cytotoxic T-cells to specifically identify and destroy malignant clones.',
    },
    author: { fa: 'دکتر کاوه مهرآرا (انکولوژیست بالینی)', en: 'Dr. Kaveh Mehrara, Oncologist' },
    reviewer: { fa: 'دکتر پروانه علیزاده (فوق‌تخصص هماتولوژی)', en: 'Reviewed by Dr. Parvaneh Alizadeh' },
    readTimeMin: 8,
    publishDate: '۱۴۰۳/۰۶/۲۸',
    image: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&q=80&w=600',
    status: 'PUBLISHED',
  },
  {
    id: 'art-minimally-invasive',
    title: {
      fa: 'چرا جراحی روباتیک دوره نقاهت را از چند هفته به ۴۸ ساعت کاهش داده است؟',
      en: 'How Robotic Surgery Shrinks Recovery Time from Weeks to 48 Hours',
    },
    category: { fa: 'فناوری‌های جراحی', en: 'Surgical Tech' },
    excerpt: {
      fa: 'برش‌های میکرو، عدم نیاز به اکستنشن عضلانی و کاهش خونریزی به کمتر از ۵۰ سی‌سی، بیماران جراحی پروستات و فتق را ظرف دو روز به کار بازمی‌گرداند.',
      en: 'Microscopic incisions, minimal muscle trauma, and blood loss below 50cc enable patients to safely return to work within days.',
    },
    author: { fa: 'دکتر آرش پارسانیا (جراح روباتیک)', en: 'Dr. Arash Parsania' },
    reviewer: { fa: 'کمیته علمی اتاق‌های عمل ابن‌سینا', en: 'Avicenna Surgical Review Board' },
    readTimeMin: 5,
    publishDate: '۱۴۰۳/۰۷/۰۱',
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=600',
    status: 'PUBLISHED',
  },
];

export const INITIAL_APPOINTMENTS: AppointmentRecord[] = [
  {
    id: 'apt-9081',
    trackingCode: 'AVI-2024-9081',
    doctorId: 'doc-keyhani',
    patientName: 'علی‌رضا مرادی',
    patientNationalId: '0019482011',
    patientPhone: '09123456789',
    date: '1403/07/15',
    slot: '10:00',
    status: 'CONFIRMED',
    departmentName: { fa: 'مرکز جامع قلب و عروق', en: 'Heart & Vascular Center' },
    serviceName: { fa: 'ویزیت و اکوکاردیوگرافی تخصصی', en: 'Consultation & 4D Echo' },
    createdAt: '2024-09-18T10:15:00Z',
    paymentStatus: 'PAID',
    notes: 'بیمار دارای سابقه استنت‌گذاری سال ۱۴۰۱ است.',
  },
  {
    id: 'apt-9082',
    trackingCode: 'AVI-2024-9082',
    doctorId: 'doc-alizadeh',
    patientName: 'سارا کاظمی',
    patientNationalId: '0078123901',
    patientPhone: '09129876543',
    date: '1403/07/18',
    slot: '16:00',
    status: 'CONFIRMED',
    departmentName: { fa: 'انستیتو کانسر و ژن‌درمانی', en: 'Cancer & Gene Therapy' },
    serviceName: { fa: 'بررسی توموربورد و نتایج ایمونوهیستوشیمی', en: 'Tumor Board & IHC Review' },
    createdAt: '2024-09-19T14:20:00Z',
    paymentStatus: 'PAID',
  },
];

export const MOCK_LAB_RESULTS: LabResult[] = [
  {
    id: 'lab-401',
    testName: { fa: 'پانل جامع بیوشیمی و هورمون‌های متابولیک (CMP Extended)', en: 'Comprehensive Metabolic Panel Extended (CMP)' },
    doctorName: { fa: 'پروفسور مسعود کیهانی', en: 'Prof. Masoud Keyhani' },
    date: '۱۴۰۳/۰۶/۲۹',
    status: 'READY',
    laboratorySection: { fa: 'آزمایشگاه تخصصی بیوشیمی بالینی', en: 'Clinical Biochemistry Lab' },
    fileSize: '1.4 MB (PDF Sign)',
    downloadToken: 'tok-sec-88192a',
  },
  {
    id: 'lab-402',
    testName: { fa: 'سی‌تی آنژیوگرافی عروق کرونر با بازسازی سه‌بعدی (256-Slice)', en: '256-Slice Coronary CT Angiography 3D' },
    doctorName: { fa: 'دکتر وحید صبوری (رادیولوژیست)', en: 'Dr. Vahid Sabouri, Radiologist' },
    date: '۱۴۰۳/۰۶/۲۷',
    status: 'READY',
    laboratorySection: { fa: 'مرکز تصویربرداری پیشرفته و آرشیو PACS', en: 'Advanced Imaging & PACS Archive' },
    fileSize: '48.2 MB (DICOM/PDF)',
    downloadToken: 'tok-sec-33109b',
  },
  {
    id: 'lab-403',
    testName: { fa: 'آنالیز توالی‌یابی جهش‌های ژنی تومور (NGS Panel 500 Genes)', en: 'Next-Generation Gene Sequencing 500-Gene Panel' },
    doctorName: { fa: 'دکتر پروانه علیزاده', en: 'Dr. Parvaneh Alizadeh' },
    date: '۱۴۰۳/۰۷/۰۱',
    status: 'PROCESSING',
    laboratorySection: { fa: 'انستیتو ژنتیک پزشکی مولکولی', en: 'Molecular Medical Genetics' },
    fileSize: 'در حال تکمیل',
    downloadToken: '',
  },
];

export const MOCK_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'aud-101',
    timestamp: '2024-09-20 17:42:10',
    actor: 'Dr. Keyhani (Staff ID: 104)',
    role: 'Practitioner',
    action: 'RESOURCE_ACCESS_AUTHORIZED',
    resource: 'EHR_PATIENT_RECORD_0019482011',
    status: 'SUCCESS',
    ipHash: 'sha256-e89a..b4',
    details: 'Accessed active patient cardiology history during scheduled appointment window.',
  },
  {
    id: 'aud-102',
    timestamp: '2024-09-20 16:30:05',
    actor: 'Anonymous Caller (Session: s_8a01)',
    role: 'Public_Guest',
    action: 'UNAUTHORIZED_IDOR_QUERY_BLOCKED',
    resource: 'PATIENT_INVOICE_INV-99042',
    status: 'DENIED',
    ipHash: 'sha256-11ca..79',
    details: 'Prevented unauthenticated cross-tenant access attempt to billing object. OWASP ASVS 4.1 triggered.',
  },
  {
    id: 'aud-103',
    timestamp: '2024-09-20 15:12:44',
    actor: 'System Booking Engine',
    role: 'Domain_Service',
    action: 'SLOT_MUTEX_ACQUIRED',
    resource: 'APPOINTMENT_SLOT_KEYHANI_20241006_1000',
    status: 'SUCCESS',
    ipHash: 'internal_worker',
    details: 'Distributed lock acquired. Prevented potential concurrent double booking attempt.',
  },
  {
    id: 'aud-104',
    timestamp: '2024-09-20 14:05:19',
    actor: 'Admin_Cms_Editor',
    role: 'Content_Manager',
    action: 'CONTENT_STAGE_TRANSITION',
    resource: 'ARTICLE_art-heart-signs',
    status: 'SUCCESS',
    ipHash: 'sha256-55fa..33',
    details: 'Article approved by Faculty Member Prof. Keyhani and promoted to PUBLISHED status.',
  },
];

export const COMMERCIAL_TIERS: CommercialTier[] = [
  {
    id: 'tier-essential',
    name: { fa: 'پلن پایه: وب‌سایت معرفی و نوبت‌دهی مقدماتی', en: 'Tier 1: Essential Hospital Portal' },
    category: 'Essential',
    price: { fa: '۱۰۰ میلیون تومان', en: '100,000,000 Tomans' },
    description: {
      fa: 'مناسب برای کلینیک‌های تخصصی و مراکز درمانی متوسط که نیازمند حضور آنلاین باوقار، معرفی اعضای هیئت علمی و سیستم ثبت درخواست نوبت هستند.',
      en: 'Engineered for medical centers seeking an authoritative brand presence, faculty directory, and structured appointment inquiries.',
    },
    highlightFeatures: {
      fa: [
        'پرتال واکنش‌گرا و سریع معرفی دپارتمان‌ها و پزشکان',
        'فرم‌های اعتبارسنجی‌شده ثبت نوبت و رهگیری پیامکی',
        'پنل مدیریت محتوای CMS استاندارد (پزشکان، مقالات، خدمات)',
        'پشتیبانی کامل از زبان‌های فارسی (RTL) و انگلیسی (LTR)',
      ],
      en: [
        'Responsive, high-speed department and clinical showcase',
        'Validated appointment booking form with SMS tracking',
        'Standard CMS panel (Doctors, News, Services, FAQ)',
        'Full bilingual support for Persian (RTL) and English (LTR)',
      ],
    },
    architectureSpecs: {
      fa: ['Next.js App Router + SSR', 'Tailwind CSS UI Kit', 'Single Database Monolith', 'Standard RBAC'],
      en: ['Next.js App Router + SSR', 'Tailwind CSS UI Kit', 'Single Database Monolith', 'Standard RBAC'],
    },
    targetMarket: { fa: 'کلینیک‌های درمانی، مراکز جراحی محدود، پلی‌کلینیک‌ها', en: 'Specialty Clinics & Ambulatory Centers' },
  },
  {
    id: 'tier-professional',
    name: { fa: 'پلن حرفه‌ای: پلتفرم بالینی هوشمند و پرتال بیمار', en: 'Tier 2: Professional Clinical Platform' },
    category: 'Professional',
    price: { fa: '۲۲۰ میلیون تومان', en: '220,000,000 Tomans' },
    badge: { fa: 'رشد و مقیاس‌پذیری بالینی', en: 'Clinical Scalability' },
    description: {
      fa: 'پلتفرم جامع دیجیتال برای بیمارستان‌های جنرال و فوق‌تخصصی شامل موتور نوبت‌دهی بلادرنگ ضد دابل‌بوکینگ، پرتال تعاملی بیماران و کنسول مدیریت بالینی.',
      en: 'Comprehensive digital infrastructure for general and tertiary hospitals featuring real-time concurrency-safe scheduling and patient portal.',
    },
    highlightFeatures: {
      fa: [
        'موتور نوبت‌دهی هوشمند با پیشگیری قطعی از Double Booking و اسلات‌های زنده',
        'پرتال بیمار با خلاصه پرونده سلامت (EHR)، سوابق نوبت و جواب آزمایش‌ها',
        'فضای کاری پزشک (Doctor Workspace) با صف ویزیت روزانه و مدیریت ساعات کاری',
        'سیستم چندزبانه خودکار با سئوی پیشرفته رتبه ۱ گوگل در کلیدواژه‌های پزشکی',
        'مخزن امن مدارک پزشکی منطبق با الزامات محرمانگی بیمار',
      ],
      en: [
        'Transactional scheduling engine with concurrency locks & zero double-booking',
        'Patient Portal with health summary, lab results, and appointment control',
        'Doctor Workspace with daily queue management and shift scheduling',
        'Medical SEO optimization targeting top rankings for specialized care',
        'Secure isolated storage for patient medical documents and reports',
      ],
    },
    architectureSpecs: {
      fa: ['Modular Monolith', 'Server-side Authorization (Zero Trust)', 'Distributed Slot Locks', 'OWASP ASVS Compliance Level 2'],
      en: ['Modular Monolith', 'Server-side Authorization (Zero Trust)', 'Distributed Slot Locks', 'OWASP ASVS Compliance Level 2'],
    },
    targetMarket: { fa: 'بیمارستان‌های جنرال، انستیتوهای تخصصی ۲۰۰ تا ۵۰۰ تختخوابی', en: 'General Hospitals & 200-500 Bed Centers' },
  },
  {
    id: 'tier-enterprise',
    name: { fa: 'پلن سازمانی: زیست‌بوم جامع سلامت و یکپارچه‌سازی HIS', en: 'Tier 3: Enterprise Digital Health Ecosystem' },
    category: 'Enterprise',
    price: { fa: '۳۵۰ میلیون تومان', en: '350,000,000 Tomans' },
    badge: { fa: 'ویژه بیمارستان‌ها و مراکز درمانی پیشرفته', en: 'Advanced Hospital & Network Grade' },
    description: {
      fa: 'راهکار تراز اول برای مجموعه‌های بزرگ دانشگاهی و زنجیره بیمارستانی همراه با یکپارچه‌سازی کامل با سامانه‌های بیمارستانی (HIS/LIS/PACS)، درگاه پرداخت و امنیت بانکی.',
      en: 'Top-tier medical architecture tailored for hospital networks, complete with HIS/LIS/PACS integration adapters, online copayments, and high availability.',
    },
    highlightFeatures: {
      fa: [
        'تمامی امکانات پلن حرفه‌ای به همراه درگاه پرداخت و تسویه حساب آنلاین',
        'لایه‌های انتزاعی و وب‌هوک اتصال به سامانه‌های HIS، پکس رادیولوژی و آزمایشگاه',
        'مرکز اعلان‌های چندکاناله اتوماتیک (SMS، ایمیل و نوتیفیکیشن بلادرنگ)',
        'سیستم مدیریت چندمرکزی (چند شعبه بیمارستانی در یک پلتفرم متمرکز)',
        'پایش امنیتی و ممیزی رویدادهای دسترسی سازگار با بازرسی‌های وزارت بهداشت و JCI',
      ],
      en: [
        'All Professional capabilities plus payment gateways & online billing reconciliations',
        'Integration adapters for hospital HIS, laboratory LIS, and radiology PACS',
        'Multi-channel notification engine (SMS, Email, Push Reminders)',
        'Multi-facility campus routing (multiple hospital branches in one system)',
        'High-security audit trails and compliance logging for JCI accreditation',
      ],
    },
    architectureSpecs: {
      fa: ['High Availability Cluster', 'Micro-services / Clean Architecture', 'Dedicated PACS Proxy', 'OWASP ASVS Level 3 Verified'],
      en: ['High Availability Cluster', 'Micro-services / Clean Architecture', 'Dedicated PACS Proxy', 'OWASP ASVS Level 3 Verified'],
    },
    targetMarket: { fa: 'بیمارستان‌های بین‌المللی، هلدینگ‌های سلامت، بیمارستان‌های دانشگاهی', en: 'International Hospitals, University Campuses & Health Groups' },
  },
  {
    id: 'tier-platform',
    name: { fa: 'پلن پلتفرم سلامت: تله‌مدیسین، تبادل داده FHIR و پرونده ملی', en: 'Tier 4: National Digital Health & Telemedicine Platform' },
    category: 'Digital Health Platform',
    price: { fa: '۵۸۰ میلیون تومان', en: '580,000,000 Tomans' },
    badge: { fa: 'آینده‌نگر و فرامرزی', en: 'Next-Gen Interoperable' },
    description: {
      fa: 'زیرساخت فرامرزی دیجیتال با پشتیبانی از پروتکل‌های جهانی HL7 FHIR، تله‌مدیسین رمزنگاری‌شده ویدئویی، پزشکی از راه دور و گردشگری سلامت (IPD).',
      en: 'Cross-border digital health platform with HL7 FHIR interoperability, encrypted WebRTC telemedicine, and international medical tourism workflows.',
    },
    highlightFeatures: {
      fa: [
        'پلتفرم ویزیت تصویری آنلاین امن بدون نیاز به نصب نرم‌افزار جانبی',
        'سازگاری کامل مدل داده با استانداردهای تبادل سلامت جهانی HL7 FHIR v6.0',
        'پرتال چندزبانه گردشگری سلامت (IPD) با پرداخت ارزی و ترانسفر هوشمند',
        'تریاژ کمکی هوشمند و پایش سلامت از راه دور (Remote Patient Monitoring)',
      ],
      en: [
        'Encrypted browser-based WebRTC telemedicine video consultations',
        'Native HL7 FHIR v6.0 interoperable resources and data pipelines',
        'International Patient Department (IPD) with multi-currency copay and logistics',
        'Automated clinical triage and Remote Patient Monitoring telemetry',
      ],
    },
    architectureSpecs: {
      fa: ['FHIR REST API Server', 'WebRTC Signaling Clusters', 'End-to-End Encrypted Data Pipes', 'Geo-distributed CDN'],
      en: ['FHIR REST API Server', 'WebRTC Signaling Clusters', 'End-to-End Encrypted Data Pipes', 'Geo-distributed CDN'],
    },
    targetMarket: { fa: 'وزارتخانه‌های بهداشت، شبکه‌های ملی سلامت و قطب‌های مدیکال توریسم', en: 'National Health Networks & Medical Tourism Hubs' },
  },
];
